service: zips3files

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action: "s3:*" # Allow all s3 actions. -> its probably good to lock this down but for demo reasons this is quicker.
            # - "s3:PutObject"
            # - "s3:ListBucket"
            # - "s3:GetObject"
            # - "s3:PutObjectAcl"
          Resource: "arn:aws:s3:::${self:custom.bucket}/*"

package:
  patterns:
    - '!node_modules/**'
    - '!package.json'
    - '!package-lock.json'
    - '!.serverless/**'
    - 'Layers/*'

# Lambda funtions
functions:
  s3-zipper:
    handler: handler.handler
    description: Zips files after they are uploaded to the ${self:buckets.test-zipper} s3 bucket
    layers: 
      - { Ref: ModulesLambdaLayer }
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          existing: true

# Define the layers
layers:
  modules:
    path: layer

# Use env var for bucket or default to `s3-test-zipper`
buckets:
  test-zipper: ${env:BUCKET, 's3-test-zipper'}
